---
# yYmllint disable rule:line-length
- ansible.builtin.set_fact:
    instance_conf_dict:
      # eslint-disable-next-line max-len
      address: '{{ instance_info.networkInterfaces.0.accessConfigs.0.natIP if molecule_yml.driver.external_access else instance_info.networkInterfaces.0.networkIP }}'
      identity_file: '{{ ssh_identity_file }}'
      instance: '{{ instance_info.name }}'
      instance_os_type: '{{ molecule_yml.driver.instance_os_type }}'

      port: '22'
      user: "{{ lookup('env','USER') }}"
  loop: '{{ server.results }}'
  loop_control:
    loop_var: instance_info
  name: Populate instance config dict Linux
  no_log: true
  register: instance_conf_dict

- ansible.builtin.set_fact:
    instance_conf_dict:
      # eslint-disable-next-line max-len
      address: '{{ instance_info.networkInterfaces.0.accessConfigs.0.natIP if molecule_yml.driver.external_access else instance_info.networkInterfaces.0.networkIP }}'
      instance: '{{ instance_info.name }}'
      instance_os_type: '{{ molecule_yml.driver.instance_os_type }}'

      password: '{{ instance_info.password }}'
      port: '{{ instance_info.winrm_port | default(5986) }}'
      user: molecule_usr
      winrm_server_cert_validation: "{{ molecule_yml.driver.winrm_server_cert_validation | default('ignore') }}"
      winrm_transport: "{{ molecule_yml.driver.winrm_transport | default('ntlm') }}"
  loop: '{{ win_instances }}'
  loop_control:
    loop_var: instance_info
  name: Populate instance config dict Windows
  no_log: true
  register: instance_conf_dict

- ansible.builtin.set_fact:
    instance_conf: {}

  name: Wipe out instance config
- ansible.builtin.set_fact:
    instance_conf: "{{ instance_conf_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

  name: Convert instance config dict to a list
- ansible.builtin.copy:
    content: '{{ instance_conf }}'
    dest: '{{ molecule_instance_config }}'
    mode: '0600'
  name: Dump instance config
