---
dependency:
  command: |
    if type task > /dev/null; then
      task ansible:test:molecule:dependencies
    else
      ansible-galaxy install --ignore-errors -r requirements.yml
    fi
  name: shell
provisioner:
  name: ansible
  options:
    vvv: true
  playbooks:
    converge: ../converge.yml
    docker:
      create: ../../.config/molecule/docker.create.yml
      destroy: ../../.config/molecule/docker.destroy.yml
    gce:
      create: ../../.config/molecule/gce.create.yml
      destroy: ../../.config/molecule/gce.destroy.yml
    prepare: ../../.config/molecule/prepare.yml
    vagrant:
      create: ../../.config/molecule/vagrant.create.yml
      destroy: ../../.config/molecule/vagrant.destroy.yml
verifier:
  name: ansible
