---
# yYmllint disable rule:line-length
- hosts: localhost
  name: Update platforms
  tasks:
    - name: Filtering platforms list using the group defined in the MOLECULE_GROUP environment variable
      set_fact:
        # eslint-disable-next-line max-len
        molecule_yml: "{{ molecule_yml | combine({'platforms': (molecule_yml.platforms | selectattr('groups', 'contains', lookup('env', 'MOLECULE_GROUP')))}) }}"
      when: ansible_env.MOLECULE_GROUP is defined

- connection: local
  gather_facts: false
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml
      name: Import main handler tasks
  hosts: localhost
  name: Create
  no_log: '{{ molecule_no_log }}'
  tasks:
    - ansible.builtin.assert:
        fail_msg: instance_os_type is possible only to specify linux or windows either

        that:
          - molecule_yml.driver.instance_os_type | lower == "linux" or
            molecule_yml.driver.instance_os_type | lower == "windows"
      name: Make sure the group contains only Linux hosts or Windows hosts
    - ansible.builtin.include_tasks: tasks/create_linux_instance.yml
      name: Include create_linux_instance tasks
      when:
        - molecule_yml.driver.instance_os_type  | lower == "linux"

    - ansible.builtin.include_tasks: tasks/create_windows_instance.yml
      name: Include create_windows_instance tasks
      when:
        - molecule_yml.driver.instance_os_type  | lower == "windows"
  vars:
    gcp_project_id: "{{ molecule_yml.driver.project_id | default(lookup('env', 'GCE_PROJECT_ID')) }}"
    ssh_identity_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
