---
# yYmllint disable rule:line-length
- hosts: localhost
  name: Update platforms
  tasks:
    - name: Filtering platforms list using the group defined in the MOLECULE_GROUP environment variable
      set_fact:
        # eslint-disable-next-line max-len
        molecule_yml: "{{ molecule_yml | combine({'platforms': (molecule_yml.platforms | selectattr('groups', 'contains', lookup('env', 'MOLECULE_GROUP')))}) }}"
      when: ansible_env.MOLECULE_GROUP is defined

- hosts: localhost
  name: Destroy
  connection: local
  gather_facts: false
  no_log: '{{ molecule_no_log }}'
  tasks:
    - loop_control:
        label: '{{ item.name }}'
      name: Destroy molecule instance(s)
      vagrant:
        instance_name: '{{ item.name }}'
        platform_box: '{{ item.box | default(omit) }}'
        provider_name: '{{ molecule_yml.driver.provider.name | default(omit, true) }}'
        provider_options: '{{ item.provider_options | default(omit) }}'
        provider_raw_config_args: '{{ item.provider_raw_config_args | default(omit) }}'
        force_stop: '{{ item.force_stop | default(true) }}'
        state: destroy
      register: server
      with_items: '{{ molecule_yml.platforms }}'
      no_log: false

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    -         # Molecule managed
          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: '{{ molecule_instance_config }}'
        mode: 0600
      copy:
        content: |
  name: Dump instance config # noqa 503
      when: server.changed | bool
